### ISSUE TITLE
Make it python 2.7 compatible. 

### ISSUE THREAD

**Issue by wgaylord** [controversial/PyBB#1]
This way it can be used from pythonista. (Which would be cool.)

**Comment by controversial** [comment]
Yep. I actually wrote what I have so far in Pythonista, but in the Pythonista 3 beta. It'm actually working on something else now (in a private repo) but I'll try and get this done.

In the meantime, you're welcome to submit a pull request, the changes should be pretty trivial.

**Comment by wgaylord** [comment]
Okay. The only changes I really see have to do with urllib so yeah sould be a piece of cake.

**Comment by controversial** [comment]
Actually just did it. I'll update in a sec.

**Comment by wgaylord** [comment]
Okay. Thanks! :+1:

**Comment by controversial** [comment]
Should be fixed with eccfe439d7b2c4bf0291174c63cc3a2aaf7f7dbb

**Comment by controversial** [comment]
Thanks for pointing that out, though. I didn't know it would be so easy 😉

Sorry it took a while for me to commit, I had to do something else quickly.
